### ISSUE TITLE
Sending Yaw Commands

### ISSUE THREAD

**Issue by matthew-givens** [Jaeyoung-Lim/mavros_controllers#114]
Hi,

Great work on the package! I'm pretty new to ROS (and C++ for that matter). I've gotten everything working in the simulation and I have a real drone set up with position feedback. Now I'm looking to have the simulated drone point at the center of the circle at all times (then I'll test it with the real drone). I know how to generate the appropriate yaw quaternion command (using the theta angle about the circle) but I don't know how to implement this in the code. I've written a 'getOrientation' function in the shapetrajectory.cpp file and called it later in the file but this doesn't seem to work. Any guidance on this would be appreciated!

Thanks!

**Comment by Jaeyoung-Lim** [comment]
@matthew-givens Thank you for the nice words. It would be great if you can provide feedback or even better if you can contribute to the code base. 

You can set yaw by simply sending topics over `~reference/yaw` message

**Comment by matthew-givens** [comment]
Thanks! With some effort, I wrote a package that subscribes to the `/mavros/local_position/pose` topic, calculates my desired yaw, and publishes Float32 yaw messages to the `/reference/yaw` topic. And it works! 

If I create anything worth sharing I will definitely try to contribute.
