### ISSUE TITLE
[Mavros -2] Has died

### ISSUE THREAD

**Issue by Robby119** [Jaeyoung-Lim/mavros_controllers#119]
need help, there's problem when i run roslaunch geometric_controller stil_trajectory_track_circle.launch 
![Screenshot from 2020-02-11 14-15-57](https://user-images.githubusercontent.com/55482771/74217202-67b8cd00-4cd9-11ea-9733-d5c7830b0f74.png)

**Comment by Jaeyoung-Lim** [comment]
@Robby119 Can you run PX4 SITL gazebo?

**Comment by Robby119** [comment]
it's done, i've reinstalled mavros. Maybe i missed some steps before.
Another question, why the drone will fall in the end (it's about 5-10 minutes after start) it's supposed to be like that or it's just me?

**Comment by Jaeyoung-Lim** [comment]
@Robby119 No it shouldn't be like that. Do you have a log?

**Comment by Jaeyoung-Lim** [comment]
@Robby119 Please reopen if the issue persists
