### ISSUE TITLE
is it usable for hexacopter ?

### ISSUE THREAD

**Issue by Robby119** [Jaeyoung-Lim/mavros_controllers#122]
i'm doing my research but using hexacopter, i'm wondering is it usable for hexacopter?  if it isn't what should i change from your code?
thanks

**Comment by Jaeyoung-Lim** [comment]
@Robby119 It is usable for hexacopter. As long as you are running PX4, it doesn't matter which vehicle type you are using

**Comment by Robby119** [comment]
Just using it directpy or should i change some part inside the code?  Cause
as far as i know, quadcopter and hexacopter have different dynamic model
and it's sure will lead to difference angular acc

Pada tanggal Kam, 26 Mar 2020 05:45, JaeyoungLim <notifications@github.com>
menulis:

**Comment by Jaeyoung-Lim** [comment]
@Robby119 We are not using vehicle specific dynamics in this project, but rather using setpoints such as bodyrate / velocity / position which does not matter which airframe you are using

**Comment by Robby119** [comment]
Alright, thank you so much for the responses

Pada tanggal Kam, 26 Mar 2020 06:28, JaeyoungLim <notifications@github.com>
menulis:

**Comment by Robby119** [comment]
Hi, there's another issue that make me confuse, in this section you're clearly using Faesler differential flatness 
 
![image](https://user-images.grithubusercontent.com/55482771/83845693-94cf3680-a733-11ea-9c95-229d54d903d8.png),

`but when i look at that paper, the equation he's using is different from what you implement in this section.
![image](https://user-images.githubusercontent.com/55482771/83845923-f7c0cd80-a733-11ea-9c27-bf2d01d520be.png)


It's i misunderstood or what
thanks

**Comment by Jaeyoung-Lim** [comment]
@Robby119 I think that looks more or less correct, but the details might be a little different. My intention was not to implement the paper, but have a stable trajectory tracking controller.
