### ISSUE TITLE
 Build error related to FlatTarget msg

### ISSUE THREAD

**Issue by mzahana** [Jaeyoung-Lim/mavros_controllers#125]
Hi @Jaeyoung-Lim 
Following the build instructions in the README, I get the following error after `catkin build`
```sh
 fatal error: controller_msgs/FlatTarget.h: No such file or directory
 #include <controller_msgs/FlatTarget.h>
```
Do I need to modify the msg dependencies in the geometric_controllers pkg?

Here is my `catkin_ws` config, if it helps
```sh
----------------------------------------------------------
Profile:                     default
Extending:        [explicit] /opt/ros/melodic
Workspace:                   /home/arrow/catkin_ws
----------------------------------------------------------
Build Space:        [exists] /home/arrow/catkin_ws/build
Devel Space:        [exists] /home/arrow/catkin_ws/devel
Install Space:      [unused] /home/arrow/catkin_ws/install
Log Space:          [exists] /home/arrow/catkin_ws/logs
Source Space:       [exists] /home/arrow/catkin_ws/src
DESTDIR:            [unused] None
----------------------------------------------------------
Devel Space Layout:          linked
Install Space Layout:        None
----------------------------------------------------------
Additional CMake Args:       -DCMAKE_BUILD_TYPE=Release
Additional Make Args:        None
Additional catkin Make Args: None
Internal Make Job Server:    True
Cache Job Environments:      False
----------------------------------------------------------
Whitelisted Packages:        None
Blacklisted Packages:        None
----------------------------------------------------------
Workspace configuration appears valid.
----------------------------------------------------------
```

**Comment by mzahana** [comment]
Solved by changing the config of the `catkin_ws` as follows
```sh
catkin config --merge-devel
```

**Comment by Jaeyoung-Lim** [comment]
@mzahana would you mind adding it to the build instructions in the readme?

**Comment by mzahana** [comment]
@Jaeyoung-Lim  here you go https://github.com/Jaeyoung-Lim/mavros_controllers/pull/126

**Comment by tejalbarnwal** [comment]
Hey @mzahana, 
How did you figure out to use the `merged` layout? and why does it make when we use a `merged` layout before we execute `catkin build`

**Comment by Jaeyoung-Lim** [comment]
@tejalbarnwal 
```
        catkin config --merge-devel
```

**Comment by tejalbarnwal** [comment]
Hey @Jaeyoung-Lim ,
First of all, thank you so much for creating this excellent repo!
Next, coming to this thread, pardon me if I came across as little confusing with my choice of words, but I wanted to know why does doing `catkin config --merge-devel` work. Doing `catkin config --merge-devel` creates a merged layout as mentioned [here](https://wiki.hanzheteng.com/development/cmake/catkin-tools#catkin-devel-space), leading to `catkin build` working perfectly without giving out the error message related to FlatTarget msg.
