### ISSUE TITLE
Parameterize initial target position

### ISSUE THREAD

**Issue by mzahana** [Jaeyoung-Lim/mavros_controllers#135]
Hi @Jaeyoung-Lim 
I see that the [initial target position](https://github.com/Jaeyoung-Lim/mavros_controllers/blob/master/geometric_controller/src/geometric_controller.cpp#L57) is hard-coded. Would it be better to parameterize it (getting it from ROS params)?

**Comment by Jaeyoung-Lim** [comment]
Yes please!

**Comment by mzahana** [comment]
Please check https://github.com/Jaeyoung-Lim/mavros_controllers/pull/136

**Comment by Jaeyoung-Lim** [comment]
@mzahana Thanks for the contribution!

Closing since fixed in #136
