### ISSUE TITLE
MODE: Unsupported FCU

### ISSUE THREAD

**Issue by Wayne-xixi** [Jaeyoung-Lim/mavros_controllers#140]
Hi Jaeyoung,

thank you for your work. I try to test the code and follow the example :roslaunch geometric_controller sitl_trajectory_track_circle.launch. Everything goes well but I got an error : MODE: Unsupported FCU. And there was no action in uav in Gazebo. Could you please help me?

**Comment by Jaeyoung-Lim** [comment]
@Wayne-xixi I think you might have the wrong mavros version.

**Comment by Jaeyoung-Lim** [comment]
@Wayne-xixi Please reopen if the issue persists
