### ISSUE TITLE
What is the reason of setting norm_thrust_const and norm_thrust_offset to 0.05 and 0.1?

### ISSUE THREAD

**Issue by rainfall1998** [Jaeyoung-Lim/mavros_controllers#143]
I am trying to get the controller work in Airsim, thus I can use Airsim API 
```
moveByAngleRatesThrottleAsync(roll_rate, pitch_rate, yaw_rate, throttle, cmd_time_)
```
while I find these two value just work perfectly in Airsim. because 0.05 * g_ + 0.1 = 0.59 (throttle), which is just the hover throttle in airsim. So I was wondering if there is any reason to set these two parameter.

**Comment by Jaeyoung-Lim** [comment]
@rainfall1998 Yes, because depending on your hardware you would need to change those values according to your system

**Comment by HenryHuYu** [comment]
> @rainfall1998 Yes, because depending on your hardware you would need to change those values according to your system

Thanks for you reply. I also have the same question. And does **norm_thrust_const** have any physical meaning? according to my understanding, it is something like "throttle per accelerate"?

**Comment by Robby119** [comment]
Hi @Jaeyoung-Lim i'm trying to understand how to calculate thrust in your code

 ratecmd(3) = std::max(0.0, std::min(1.0, norm_thrust_const_ * ref_acc.dot(zb) + norm_thrust_offset_));  // Calculate thrust

do you have paper/report that can help me to understand how it works ?

Thanks in advance

**Comment by Jaeyoung-Lim** [comment]
@Robby119 PX4 simply uses a normalized thrust (-1 ~ 1), and I am just trying to convert my metric thrust inputs into normalized thrust inputs
