### ISSUE TITLE
Add Waypoint Function

### ISSUE THREAD

**Issue by lgh5054** [Jaeyoung-Lim/mavros_controllers#145]
Hello
Thank you always for your help.
Only offboard mode seems to work on the Mavros_controller. Can't I upload the mission through QGC?

**Comment by HenryHuYu** [comment]
> Hello
> Thank you always for your help.
> Only offboard mode seems to work on the Mavros_controller. Can't I upload the mission through QGC?

I believe this controller mainly focus on the autonomous drone flying and with sensors and computations only onboard. And  to my understanding, mission mode in QGC is something more like using "mavros setpoint position", the controller here is more flexible and can do more aggressive things.

**Comment by Jaeyoung-Lim** [comment]
@lgh5054 PX4 already supports waypoint missions. Why would you want to upload a mission and run it in offboard mode?

**Comment by lgh5054** [comment]
@Jaeyoung-Lim We would like to implement the currently implemented path planning algorithm like a px4 dedicated local_planner

**Comment by Jaeyoung-Lim** [comment]
@lgh5054 Okay, then you need to implement yourself how to handle the waypoints

**Comment by lgh5054** [comment]
@Jaeyoung-Lim Thank you for your answer. Close the comment
