### ISSUE TITLE
Attitude error different from the referenced paper

### ISSUE THREAD

**Issue by quarcle** [Jaeyoung-Lim/mavros_controllers#150]
Why does the attitude controller in the [geometric_attcontroller](https://github.com/Jaeyoung-Lim/mavros_controllers/blob/master/geometric_controller/src/geometric_controller.cpp) different from the mentioned paper "Geometric tracking control
  // of a quadrotor UAV on SE (3)" by Lee, et al?

I tried to change the attitude error to be `error_att = 0.5 * matrix_hat_inv(rotmat_d.transpose() * rotmat - rotmat.transpose() * rotmat_d);` to make it similar to the paper, but it turns out that the quadcopter falls down in the Gazebo simulator. Do you know why that happens?

Many thanks.

**Comment by Jaeyoung-Lim** [comment]
@quarcle Can you share the log?

**Comment by quarcle** [comment]
Here is the log file:
[roslaunch-qeui-X71-6589.log](https://github.com/Jaeyoung-Lim/mavros_controllers/files/5261726/roslaunch-qeui-X71-6589.log)

Might that help?

There is no error shown while executing the controller, but the drone crashes after taking off and trying to follow a specified trajectory (in my case, I run `sitl_trajectory_track_circle.launch`)

**Comment by Jaeyoung-Lim** [comment]
@quarcle I meant the flight log. I do see that the equation is wrong, but not sure why it flies now

**Comment by quarcle** [comment]
Which log do you mean? I attach two logs (roslaunch log and the ulog files) as follows:
[geocontrol_logs.zip](https://github.com/Jaeyoung-Lim/mavros_controllers/files/5261966/geocontrol_logs.zip)

**Comment by quarcle** [comment]
> error_att = 0.5 * matrix_hat_inv(-rotmat_d.transpose() * rotmat + rotmat.transpose()

What do you mean?

**Comment by quarcle** [comment]
> error_att = 0.5 * matrix_hat_inv(-rotmat_d.transpose() * rotmat + rotmat.transpose()

@valenbase what does it mean?

**Comment by valenbase** [comment]
> > error_att = 0.5 * matrix_hat_inv(-rotmat_d.transpose() * rotmat + rotmat.transpose()
> 
> @valenbase what does it mean?

i mean exchange content on both sides of the symbol -

**Comment by quarcle** [comment]
Has anyone found out the problem and how to fix it?

**Comment by Jaeyoung-Lim** [comment]
@quarcle Could you clarify what the problem is?

**Comment by quarcle** [comment]
[This code](https://github.com/Jaeyoung-Lim/mavros_controllers/blob/master/geometric_controller/src/geometric_controller.cpp) line 444 uses `error_att = 0.5 * matrix_hat_inv(rotmat_d.transpose() * rotmat - rotmat.transpose() * rotmat);` while the referenced paper uses `error_att = 0.5 * matrix_hat_inv(rotmat_d.transpose() * rotmat - rotmat.transpose() * rotmat_d);`. When I changed to the error equation mentioned in the paper, the copter crashes. How should I resolve the problem?
