### ISSUE TITLE
process has died [pid 9907, exit code -6]

### ISSUE THREAD

**Issue by coldhenry** [Jaeyoung-Lim/mavros_controllers#161]
Hello Jaeyoung,

I am working on the installation of this project on a companion computer as you advised in #160 and there is another issue coming out during roslaunch.

<img src="https://user-images.githubusercontent.com/54171001/100293909-1614c280-2f3a-11eb-80fb-e931ad78eeab.png" >

**Version and platform**
Companion computer: Odroid XU4
ROS: Melodic
Ubuntu: 18.04 Bionic
PX4 Version: 1.11

Any thought is appreciated!

**Comment by Jaeyoung-Lim** [comment]
Sorry for the late response.

Are you sure you are running the latest `master`? I just ran the setup, and it is working as expected

**Comment by Jaeyoung-Lim** [comment]
@coldhenry Did you manage to solve your problem?

**Comment by Jaeyoung-Lim** [comment]
Closing since original author didn't respond.

Please reopen if you feel like this is still an issue @coldhenry
