### ISSUE TITLE
how to change the circle trajectory program into a squere trajectory

### ISSUE THREAD

**Issue by dedyebhi** [Jaeyoung-Lim/mavros_controllers#164]
Hi @ Jaeyoung-Lim,
I'm having some trouble understanding properly how to publish the path to a geometric controller which will then command / mavros / setpoints to FC by itself.
Until now I used the example you provided launched with sitl_trajectory_track_circle.launch.
Which program should you edit to change the shape trajectory to squere trajectory?

**Comment by Jaeyoung-Lim** [comment]
Duplicate of https://github.com/Jaeyoung-Lim/mavros_controllers/issues/169, closing
