### ISSUE TITLE
Kvel_ initalitation error?

### ISSUE THREAD

**Issue by pluto-project-it** [Jaeyoung-Lim/mavros_controllers#165]
In geometric_controller.cpp line 489:
Kvel_ << -Kvel_x_, -Kvel_z_, -Kvel_z_;
Shouldn't it be:
Kvel_ << -Kvel_x_, -Kvel_y_, -Kvel_z_;
?
Thank you for your work.
Giorgio Vaccarino

**Comment by Jaeyoung-Lim** [comment]
@pluto-project-it I think that looks like an error. Would you mind making a PR for the fix?

**Comment by pluto-project-it** [comment]
We are working to manage multiple MultiDOFJointTrajectoryPoint and we have heavily modified the code and is not stable yet.
Said that if you want I can do a PR with everything as memo.

**Comment by Jaeyoung-Lim** [comment]
@pluto-project-it Not sure if I follow, the ask was not to pull in all your changes, but only the fix you mentioned in the original issue

**Comment by pluto-project-it** [comment]
Did in https://github.com/Jaeyoung-Lim/mavros_controllers/pull/166#issue-568190625
