### ISSUE TITLE
geometric_controller on hexacopter

### ISSUE THREAD

**Issue by pluto-project-it** [Jaeyoung-Lim/mavros_controllers#168]
Hi all,
I would like to try using geometric_controller to fly offboard on a hexacopter.
Do you think there are any incompatibilities since the studies mentioned are about quadcopters?
Does anyone have experience with this or any advice on tuning?

**Comment by Jaeyoung-Lim** [comment]
It shouldn't matter, since we are controlling angular rates

**Comment by pluto-project-it** [comment]
I thought so but preferred your confirmation.
Thank you.

**Comment by Jaeyoung-Lim** [comment]
@pluto-project-it You can already try a hexacopter in SITL, using the `typhoon_h480` model
