### ISSUE TITLE
trajectory_publisher

### ISSUE THREAD

**Issue by dedyebhi** [Jaeyoung-Lim/mavros_controllers#170]
```
<param name="trajectory_type" value="1" />     #Trajectory_track_circle

<param name="trajectory_type" value="2" />     #Trajectory_track_lamniscate
```

why are the trajectory_type circle and lumniscate values ​​different? what makes the difference?

**Comment by Jaeyoung-Lim** [comment]
@dedyebhi That is how you choose which trajectory to publish (e.g. circle or lamniscate).

Have you tried running the code by changing the values? You will see that the reference trajectory looks different
