### ISSUE TITLE
Compatibility with Ardupilot Copter Firmware

### ISSUE THREAD

**Issue by Kavin-Kailash** [Jaeyoung-Lim/mavros_controllers#174]
Thanks for the great work. 

From the files, it is apparent that this package is intended for use with PX4 mainly. I was wondering about the compatibility with the Ardupilot Flight Stack.

**Comment by Jaeyoung-Lim** [comment]
@Kavin-Kailash Since it is using mavlink it should be overall compatible. However, there might be some subtle differences on how offboard control works and this has never been tested.

**Comment by Kavin-Kailash** [comment]
@Jaeyoung-Lim Thanks for the quick reply. From the documentation I could infer that the final setpoints sent to PX4 are mavros_msgs/AttitudeTarget and Pose Stamped , is there any way to configure geometric_controller so that in only provides a specific setpoint?

**Comment by Jaeyoung-Lim** [comment]
@Kavin-Kailash Yes you can. Depending on the setpoint you want to use, you can use either the trajectory_publisher or the geometric_controller
