### ISSUE TITLE
feedthrough_enable_ does not have a ROS parameter

### ISSUE THREAD

**Issue by mzahana** [Jaeyoung-Lim/mavros_controllers#181]
Hi @Jaeyoung-Lim 
I noticed that the [feedthrough_enable_](https://github.com/Jaeyoung-Lim/mavros_controllers/blob/master/geometric_controller/src/geometric_controller.cpp#L52) variable does not have a ROS [parameter](https://github.com/Jaeyoung-Lim/mavros_controllers/blob/master/geometric_controller/src/geometric_controller.cpp#L83-L104). Was it on purpose, or  mistakenly missed ?

**Comment by Jaeyoung-Lim** [comment]
@mzahana The intention of `feedthrough_enable_` was to configure it dynamically and not as a static parameter: https://github.com/Jaeyoung-Lim/mav_dob/blob/87086c79ccc4a40277d1f2c0aac0ea8e7400d3f4/dob_controller/src/dob_controller.cpp#L69
