### ISSUE TITLE
What are norm_thrust_const_ and norm_thrust_offset_ for?

### ISSUE THREAD

**Issue by mzahana** [Jaeyoung-Lim/mavros_controllers#182]
Hi @Jaeyoung-Lim 
Could you please provide some explanation on what [norm_thrust_offset_](https://github.com/Jaeyoung-Lim/mavros_controllers/blob/master/geometric_controller/src/geometric_controller.cpp#L94) and [norm_thrust_const_](https://github.com/Jaeyoung-Lim/mavros_controllers/blob/master/geometric_controller/src/geometric_controller.cpp#L93) are used for?
Is one of them related to the vehicle mass?
How can they be tuned?
Thanks

**Comment by mzahana** [comment]
Also, what is the effect of [attctrl_constant](https://github.com/Jaeyoung-Lim/mavros_controllers/blob/master/geometric_controller/src/geometric_controller.cpp#L92)?

**Comment by Jaeyoung-Lim** [comment]
> Could you please provide some explanation on what norm_thrust_offset_ and norm_thrust_const_ are used for?

It is the linear constants that maps the thrust values(N) into normalized thrust(0 ~ 1)

> Also, what is the effect of attctrl_constant?

You can check `tau` is (which is a time cosntant for attitude control in Brescianini, Dario, Markus Hehn, and Raffaello D'Andrea. Nonlinear quadrocopter attitude control: Technical report. ETH Zurich, 2013.

**Comment by mzahana** [comment]
@Jaeyoung-Lim Is there a recommended way of tuning such parameters for different multi-rotors?

**Comment by Jaeyoung-Lim** [comment]
@mzahana You are just mapping your thurst (N) to normalized thrust values. you can do this by measuring your thrust, or simply hand tuning it
