### ISSUE TITLE
Adding integrators to position controller

### ISSUE THREAD

**Issue by mzahana** [Jaeyoung-Lim/mavros_controllers#183]
@Jaeyoung-Lim 

I was thinking if it makes sense to add integrators to [posController](https://github.com/Jaeyoung-Lim/mavros_controllers/blob/567d9d4771b2ffb38464765e040c31e0c982a5e9/geometric_controller/src/geometric_controller.cpp#L412). This allows to get rid of steady state errors (e.g. caused by disturbance).

You can check Eq. 7 in [this paper](https://www.researchgate.net/publication/328573824_Cooperative_autonomous_search_grasping_and_delivering_in_a_treasure_hunt_scenario_by_a_team_of_unmanned_aerial_vehicles)

**Comment by Jaeyoung-Lim** [comment]
@mzahana Would be interesting to see how the performance is affected. I did not add a integrator since I was aiming for more dynamic maneuvers in this implementation, but if you can make it work reliably we can make it optional.
