### ISSUE TITLE
AirSim

### ISSUE THREAD

**Issue by brunopinto900** [Jaeyoung-Lim/mavros_controllers#184]
Hello,

Thank you for the amazing code. I intend to use this as my controller for autonomous drone racing.

Can this repo work with AirSim instead of gazebo? 

Thank you.

**Comment by Jaeyoung-Lim** [comment]
@brunopinto900 Thanks for the nice complement. Sure, this package directly interfaces with PX4, so the simulation framework doesn't matter

**Comment by Zartris** [comment]
Well this gives me some problems as I'm getting "Resource not found: gazebo_ros" so there must be some dependencies

**Comment by Jaeyoung-Lim** [comment]
@Zartris 
```
apt install ros-<ros_distro>-gazebo-ros
```

**Comment by Zartris** [comment]
Yes I got it working, I was just mentioning the dependency :) 
I just set the gazebo parameters in the launch file to be false and it fixed it.

**Comment by Jaeyoung-Lim** [comment]
@Zartris Great, anyway this seems to be unrelated to this issue
