### ISSUE TITLE
/mavros/local_position/pose not working properly

### ISSUE THREAD

**Issue by Novotendo** [Jaeyoung-Lim/mavros_controllers#187]
Hello @Jaeyoung-Lim 

I'm currently trying to use your package using a single GPS for position estimation as first test. The problem is that, when my drone is at the ground and I read the topic /mavros/local_position/pose, the X and Y are always 0.0. The rest of the values: Z, and the quaternion are correctly displayed. Maybe do I need to change a parameter in the pixhawk? I'm using:
-Pixhawk 2.4.8
-PX4 1.11.3

Thanks!

**Comment by Jaeyoung-Lim** [comment]
@Novotendo Are you sure you have a valid position estimate (e.g. GPS fix)?

**Comment by Novotendo** [comment]
Yes, I've got 3D Lock, here is a capture:
![imagen](https://user-images.githubusercontent.com/33312243/126147097-0af2eeb5-9f79-4d6d-bebf-89b508734e41.png)

**Comment by Jaeyoung-Lim** [comment]
@Novotendo Okay, and have you tried arming the vehicle?

**Comment by Novotendo** [comment]
Even armed, it is still in the same way. What is considered a valid position estimate? And how could I get it?

**Comment by Jaeyoung-Lim** [comment]
@Novotendo Can your vehicle fly in position mode?

You can look up docs.px4.io to look at estimator related information of PX4

**Comment by Novotendo** [comment]
It is set into OFFBOARD mode

**Comment by Jaeyoung-Lim** [comment]
@Novotendo If you don't have a valid position estimate, you won't be able to do anything in offboard mode. Therefore, it is important that you make sure everything works on your vehicle (flying in position / mission mode) before you put the vehicle into offboard mode.

The fact that you mention you don't have position estimates just means that your EKF is not able to have a valid position estimate. Therefore you need to fix this problem first before you interact with the vehicle with mavros

**Comment by Novotendo** [comment]
And which EKF params should be set for a vehicle using just GPS data?

**Comment by Jaeyoung-Lim** [comment]
@Novotendo You cannot use just GPS data. Please go through the PX4 documentation: https://docs.px4.io/master/en/advanced_config/tuning_the_ecl_ekf.html since it is explained why this is the case

**Comment by Novotendo** [comment]
Yes, you were right @Jaeyoung-Lim ! And one more question: do you know how to "reset" the current position of the drone via mavros to (0,0,0)?
