### ISSUE TITLE
Mavros_controllers not working with px4 v 1.11.0

### ISSUE THREAD

**Issue by shubham-shahh** [Jaeyoung-Lim/mavros_controllers#194]
Hi, I am trying to use Mavros controllers with [this](https://github.com/HKPolyU-UAV/E2ES) repo and they are using px4 v 1.11.0 and I am unable to take off with mavros_controllers in the repo mentioned above
@Jaeyoung-Lim 

thanks

**Comment by shubham-shahh** [comment]
Hi, I am trying to use [this](https://github.com/ZJU-FAST-Lab/ego-planner) planner along with [E2ES](https://github.com/HKPolyU-UAV/E2ES) simulation. I am passing the trajectory obtained from the planner to mavros controller and generating attitude controls and passing it to e2es simulation and the quad is not responding to the output of the mavros controllers

**Comment by Jaeyoung-Lim** [comment]
@shubham-shahh I suspect that you are publishing setpoints to the wrong topics.

**Comment by shubham-shahh** [comment]
> @shubham-shahh I suspect that you are publishing setpoints to the wrong topics.

It was not related to topics, there were some version conflicts. I am sorry I didn't post a update. 

thanks
