### ISSUE TITLE
geometric_attcontroller function attiitude error formula typo 

### ISSUE THREAD

**Issue by sligeek100** [Jaeyoung-Lim/mavros_controllers#195]
Hi Jaeyoung
-- In geometric_controller.cpp function geometric_attcontroller, error_att = 1/2 * matrix_hat_inv(Rd' * R - R'**R**), should be
error_att = 1/2 * matrix_hat_inv(Rd'*R - R'**Rd**), then it can match the paper 'Geometric tracking control of a quadrotor UAV on SE (3)' CDC. 2010. 

-- or u defined a new att_error different from the paper's ? 
edits:
-- the position controller gains Kp, and Kv need be re-runed

**Comment by Jaeyoung-Lim** [comment]
@sligeek100 Thanks for reporting this,

indeed, I think you might be right. Would you be able to make a PR with the fix?

**Comment by Jaeyoung-Lim** [comment]
@sligeek100 Probably also a bug introduced by recent mavros. Would you be able to create a fix for this?
