### ISSUE TITLE
[Feature] Trajectory Generation

### ISSUE THREAD

**Issue by Jaeyoung-Lim** [Jaeyoung-Lim/mavros_controllers#2]
[mav_trajectory_generation](https://github.com/ethz-asl/mav_trajectory_generation) looks like a good framework for the 'generation' of trajectories.

A demo example and necessary interfaces should be created
- [ ] Try trajectory generation
- [x] Create interface for trajectory representation
- [ ] Verify this is working together

**Comment by marcusabate** [comment]
@Jaeyoung-Lim I've been working on a project utilizing [waypoint_navigator](https://github.com/ethz-asl/waypoint_navigator) as the framework for generating trajectories. You may remember michaelkapteyn did this as well.

If you'd like to take a look at [my fork](https://github.com/marcusabate/mavros_controllers) you'll see the necessary changes to implement this. I can create a pr if you'd like.

**Comment by Jaeyoung-Lim** [comment]
@marcusabate That is a nice implementation! A PR will be appreciated :smile:
