### ISSUE TITLE
More controllers

### ISSUE THREAD

**Issue by brunopinto900** [Jaeyoung-Lim/mavros_controllers#207]
Sorry for opening another issue. Do you have any plans to add other controllers? If so, can you tell the reference papers? For example i was planning do add this https://foehnx.github.io/publication/icra18/ but its already done here https://github.com/llanesc/lqr-tracking. 

Thank you.

**Comment by Jaeyoung-Lim** [comment]
@brunopinto900 Would be definitely cool to have that as part of this package, and we can then start doing benchmarks etc

**Comment by Jaeyoung-Lim** [comment]
@brunopinto900 Personally, I would be interested on adding a predictive controller, e.g. a MPPI(Model Predictive Path Integral Controller) or a MPCC(Model Predictive Contouring Control) but probably a lot more work than a full state LQR :wink:

**Comment by brunopinto900** [comment]
A model predictive control with collision avoidance would be nice. We can start by first implementing a linear MPC with no collision avoidance, then start integrate collision avoidance with RRT using OMPL (similar to PX4-Obstacle_avoidance repo). The MPPI is nice, but the math is so dull haha.
