### ISSUE TITLE
Obstacle avoidance Model Predictive Control

### ISSUE THREAD

**Issue by brunopinto900** [Jaeyoung-Lim/mavros_controllers#209]
Hello,

I am integrating https://github.com/llanesc/lqr-tracking into this package. I can leverage that to implement a Model Predictive Controller. The goal is to use the MPC as an obstacle avoidance local planner, rather than just a plain controller. However this gets out the scope of this package. Can you give me advice/suggestions on how to approach this? 

Thank you.

**Comment by Jaeyoung-Lim** [comment]
@brunopinto900 Not sure if I understand this correctly.

The state dependent LQR is not a predictive controller. How would this be related to a Model Predictive Controller?

> However this gets out the scope of this package

I am not aware of what the scope of this package should be :smile: Could you elaborate?

**Comment by Jaeyoung-Lim** [comment]
@brunopinto900 Any updates regarding the LQR?

**Comment by brunopinto900** [comment]
@Jaeyoung-Lim Already coded everything. Compiles and the logic is correct, however the SITL says on the terminal that the battery is below the limit haha. I was working on the PX4 Obstacle Avoidance.

**Comment by Jaeyoung-Lim** [comment]
@brunopinto900 Thanks for the update!

**Comment by brunopinto900** [comment]
@Jaeyoung-Lim Yes. Will do it in the next minutes.

**Comment by Jaeyoung-Lim** [comment]
PR: https://github.com/Jaeyoung-Lim/mavros_controllers/pull/210
