### ISSUE TITLE
I don't know where the drone's trajectory is decided.

### ISSUE THREAD

**Issue by romaster93** [Jaeyoung-Lim/mavros_controllers#214]
hi

I am studying this package. I'm looking at the example and studying the code, 
but I don't know what message to send the target point to the drone.

I think that in mavros_controllers/geometric_controller/src/geometric_controller.cpp,
the drone with px4 can change the mode, arminig, and set the target point. 

But I don't know where the command to get the drone to the target is coming from. May I ask for some advice?

**Comment by Jaeyoung-Lim** [comment]
@romaster93 The reference is published from the `trajectory-publisher`
