### ISSUE TITLE
Gazebo simulation: drone in Gazebo not moving but frames in Rviz moving

### ISSUE THREAD

**Issue by ZhongmouLi** [Jaeyoung-Lim/mavros_controllers#220]
Hi Guys,

I just met a very strange case when I used this package in px4-mavros-gazebo simulation.

Following the instructions [here](https://github.com/Jaeyoung-Lim/mavros_controllers), I am able to run both

- `roslaunch px4 posix_sitl.launch` to get a Gazebo world with a iris drone model

- `roslaunch geometric_controller sitl_trajectory_track_circle.launch` to run the controller without error.

But, the results are so strange:

1. drone frame in Rviz moves while drone in Gazebo does not move at all
![Screenshot from 2022-06-22 10-53-06](https://user-images.githubusercontent.com/21055404/175000571-7372ce52-ff32-4376-a8a6-dd3e0631dcb6.png)
![Screenshot from 2022-06-22 10-53-00](https://user-images.githubusercontent.com/21055404/175000654-56a4c6d6-1e63-4a6d-813e-145491a314fe.png)
2. I use Qgroundcontrol to arm the drone, but it cannot be switched to offboard mode
![Screenshot from 2022-06-22 10-55-51](https://user-images.githubusercontent.com/21055404/175001269-efc3ab9b-1984-43f1-a087-831f661ad572.png)

This is so strange to me. Do you have any ideas how to solve it?

**Comment by Jaeyoung-Lim** [comment]
@ZhongmouLi Thanks for the update!
