### ISSUE TITLE
question about mavros topic local_position?

### ISSUE THREAD

**Issue by maulanaazhari** [Jaeyoung-Lim/mavros_controllers#234]
1. why in the code you are using "**local_position/pose**" and "**local_position/velocity_loca**l" topics instead of "**local_position/odom**" topic? since the odom topic has bot pose and twist/velocity.
2. I was trying to change the topic to the "**local_position/odom**" topic, it worked great in the simulator but somehow didn't work great in real hardware, if I plot the data in plotjuggler, I found that the update interval of "**local_position/odom**" topic was inconsistent. Is it your consideration of not using the odom topic? do you know why it happened? (green odom topic, yellow local_position topic)
![image](https://user-images.githubusercontent.com/26515714/235340442-fb795fba-2fb2-4458-b464-80163a547ed6.png)

**Comment by Jaeyoung-Lim** [comment]
@maulanaazhari I think you can use the odom topic, if you want. I simply used the local position plugin since that was what I needed for this package.
