### ISSUE TITLE
Please tell How to run this code?

### ISSUE THREAD

**Issue by ScoobyCodes** [Jaeyoung-Lim/mavros_controllers#36]
Please Provide documentation with steps to run this Code. I have succesfully installed and tested Ros px4 And mavros.
But I am still unable to run this code. Maybe I am doing something wrong.

**Comment by Jaeyoung-Lim** [comment]
@ScoobyCodes This repo is lacking documentation as I wasn't expecting more people to use this.

I will update the documentation within today thanks

**Comment by Jaeyoung-Lim** [comment]
@ScoobyCodes  I have updated the Readme

Please let me know if you have more questions, Thanks

**Comment by Jaeyoung-Lim** [comment]
@ScoobyCodes Could you confirm that this is working for you?
