### ISSUE TITLE
Reason for the error

### ISSUE THREAD

**Issue by shivamgarg1901** [Jaeyoung-Lim/mavros_controllers#58]
Hi Jaeyoung-Lim!
I tried to run the code as explained in the repository.The packages builds up perfectly but when I  use the roslaunch command then it shows one error which is as under-
[mavros-4] process has died [pid 10798, exit code -11, cmd /home/shivam/catkin_ws1/devel/lib/mavros/mavros_node __name:=mavros __log:=/home/shivam/.ros/log/9ef07a40-423d-11e9-b232-707781c0679d/mavros-4.log].
log file: /home/shivam/.ros/log/9ef07a40-423d-11e9-b232-707781c0679d/mavros-4*.log
As a virtue of which my drone remains stationary in gazebo.
Please help me with it.
By the way you did fantastic work!
Thanks in advance :)

**Comment by Jaeyoung-Lim** [comment]
@shivamgarg1901 Thank you for the kind words

Could you clarify on which launch file you used?

**Comment by shivamgarg1901** [comment]
> @shivamgarg1901 Thank you for the kind words
> 
> Could you clarify on which launch file you used and also post the full log of your command?

**Comment by shivamgarg1901** [comment]
roslaunch geometric_controller trajectory_track_circle.launch
After executing above command I got the error on the terminal. 
![Screenshot from 2019-03-09 15-24-04](https://user-images.githubusercontent.com/25364311/54069611-a18a8380-427f-11e9-8ab1-cf4eab798aa3.png)
Also after executing the command roslaunch mavros px4.launch.I got the error on the terminal similar to the above
![Screenshot from 2019-03-09 15-27-23](https://user-images.githubusercontent.com/25364311/54069665-e2829800-427f-11e9-949c-eed4ac73e1f8.png)
Please! help me

**Comment by Jaeyoung-Lim** [comment]
Are you trying to connect to the fcu on USB?

**Comment by shivamgarg1901** [comment]
No I just want to do it on gazebo.

**Comment by Jaeyoung-Lim** [comment]
@shivamgarg1901 Your log says your launchfile is configured to connect to USB

**Comment by shivamgarg1901** [comment]
I followed this link https://dev.px4.io/en/ros/mavros_installation.html
Is there any way I can remove the existing mavros and reinstall the new one which will fulfill my requirement?

**Comment by Jaeyoung-Lim** [comment]
@shivamgarg1901 My question was more on if you installed it from source or the binary using `apt` as the binary package is outdated.

**Comment by shivamgarg1901** [comment]
Yes I did the binary installation.

**Comment by Jaeyoung-Lim** [comment]
@shivamgarg1901 You need to install it from source. Sorry for not being clear on the documentation. This was due to a recent regression on the mavros side.

**Comment by shivamgarg1901** [comment]
It's completely fine can you please give me the sequence of commands to do source installation? Also How could I get rid of that already installed binary mavros?

**Comment by Jaeyoung-Lim** [comment]
@shivamgarg1901 It is in the documentation you were referring to. To remove, try

```
apt remove ros-kinetic-mavros*
```

**Comment by shivamgarg1901** [comment]
![Uploading Screenshot from 2019-03-11 13-46-09.png…]()
I did the source installation of the mavros so the previous errors are now removed but now the terminal shows this error.How could I handle this error.Please help.

**Comment by shivamgarg1901** [comment]
![Uploading Screenshot from 2019-03-11 13-46-09.png…]()
I did the source installation of the mavros so the previous errors are now removed but now the terminal shows this error.How could I handle this error.Please help.

**Comment by shivamgarg1901** [comment]
![Screenshot from 2019-03-11 13-46-09](https://user-images.githubusercontent.com/25364311/54109710-66b25800-4405-11e9-8949-7ad234bb6fea.png)
I did the source installation of the mavros so the previous errors are now removed but now the terminal shows this error.How could I handle this error.Please help.

**Comment by Jaeyoung-Lim** [comment]
@shivamgarg1901 Somehow the geometric controller launchfile is not reading the config file. Are you sure you are using the latest master of this repo?

**Comment by shivamgarg1901** [comment]
@Jaeyoung-Lim It is working fine now.Thanks for your help.You did fantastic job :)

**Comment by Jaeyoung-Lim** [comment]
@shivamgarg1901 Thats great! Glad that it works.
