### ISSUE TITLE
Reference for the Equation 

### ISSUE THREAD

**Issue by shivamgarg1901** [Jaeyoung-Lim/mavros_controllers#60]
![Screenshot (81)](https://user-images.githubusercontent.com/25364311/54410638-530f3600-4712-11e9-98de-8cb92763163d.png)
Hi! Can u give me the reference for the equation used in this snippet of code? I cannot understand it plz help!
Also, can you give us references for the Disturbance observer used in the geometric controller?

**Comment by Jaeyoung-Lim** [comment]
@shivamgarg1901 It is simply a vector representation of the circle.

There is no refrenence for the disturbance observer. However, you can refer to a similar work from this paper:
Lee, Seung Jae, et al. "Robust acceleration control of a hexarotor UAV with a disturbance observer." 2016 IEEE 55th Conference on Decision and Control (CDC). IEEE, 2016.
