### ISSUE TITLE
Determining Constant Values

### ISSUE THREAD

**Issue by SourabhGupta12** [Jaeyoung-Lim/mavros_controllers#63]
HI! I was wondering how are you determining value of constants like Kpos, Kvel and att_ctrl_tau.

**Comment by Jaeyoung-Lim** [comment]
@ScoobyCodes It is a tuning parameter. It decides how aggressive you want to control your vehicle.

It can depend on various things such as how noisy your estimate is, how agile your vehicle is .etc

**Comment by Jaeyoung-Lim** [comment]
@SourabhGupta12 Does this answer your question?

**Comment by SourabhGupta12** [comment]
Hi! I was actually looking for some mathematical Model to determine these constants. Have you used gradient descent and optimized the possible error in your control model ?

**Comment by Jaeyoung-Lim** [comment]
@SourabhGupta12 
I did not use any optimization as these are simply parameters that tune the behavior of the controller
For example, `att_ctrl_tau` is a time constant given that we are sending angular rate commands so this is more to tune on how aggressive your attitude controller is. 

If you want to do gradient descent, you first need to define a cost to define the optimality of the gain. 

In case you want to define your own metric to define what is a more desirable behavior, I believe there are plenty of literature on optimal control that looks into this problem
