### ISSUE TITLE
Error while running the updated repository

### ISSUE THREAD

**Issue by shivamgarg1901** [Jaeyoung-Lim/mavros_controllers#80]
Hi! 
I tried to run the updated repository.It is  running everything except it is not showing any drone in the gazebo  environment and not showing any trajectory in Rviz. Here is the  screenshot of the error it is showing. 
![file](https://user-images.githubusercontent.com/25364311/56423232-c7686680-62c8-11e9-8a96-2d4fa0741486.png)
 Please help me out with the same.

**Comment by Jaeyoung-Lim** [comment]
Did you rebuild everything? Does it work if you revert the repo?

**Comment by shivamgarg1901** [comment]
Yes, It worked fine now. Thanks for your help.
Also, Jaeyoung I launched the controller benchmark file and I cannot find error calculating functionality in it. It is similar to the launching of the sitl_trajectory_track_circle.launch file.

**Comment by Jaeyoung-Lim** [comment]
@shivamgarg1901 You need to look at the code. It is not publishing any metrics yet.

**Comment by shivamgarg1901** [comment]
Sorry, My Bad. I checked it now. So how could I publish the metric or should I simply add the print statement in code to print it on the terminal?

**Comment by Jaeyoung-Lim** [comment]
@shivamgarg1901 You could do that, or you can simply publish the error metrics.

I haven't had time to do that yet, but if you do so, also a contribution will be also welcome :smile:
