### ISSUE TITLE
Where is the reference position and acceleration and jerk?

### ISSUE THREAD

**Issue by tuloski** [Jaeyoung-Lim/mavros_controllers#96]
I don't see where the position and acceleration and jerk trajectory is taken since the only topic it's subscribed is a geometry_msgs/TwistStamped. 
And they are needed by the controller for both feedback (position) and feedforward (acceleration and jerk) terms.
Also the trajectory_publisher seems only to generate a geometry_msgs/TwistStamped setpoint.

Is the position integrated from the velocity (which is btw not really correct)?

**Comment by tuloski** [comment]
Ok, looking at the code I saw that the position is taken from the twist angular (ouch!).
A little info about this in the README would be nice.

I also see there is a not documented controller_msgs::FlatTarget message which can be used to send the complete trajectory up to snap which is nice but it is not documented.

**Comment by Jaeyoung-Lim** [comment]
@tuloski Thanks for the feedback. The twist input was a hack that I put together in the initial stage of the project. I will make a fix on it
