### ISSUE TITLE
Velocity error gain

### ISSUE THREAD

**Issue by juanmed** [Jaeyoung-Lim/mavros_controllers#98]
While looking at your code, I noticed that in the gain matrix for velocity error:

https://github.com/Jaeyoung-Lim/mavros_controllers/blob/a28e89adbc9a7470577eb04d80d6d84a6e023576/geometric_controller/src/geometric_controller.cpp#L60

the 2nd element, which I suppose should corresponde to Kvel_y_, has actually the value Kvel_z_.

Should not it be as follows?
```c++
Kvel_ << -Kvel_x_, -Kvel_y_, -Kvel_z_;
```

Thanks

**Comment by Jaeyoung-Lim** [comment]
@juanmed Your right! I think the fact that the gains I we're testing was always the same, the error wasn't apparent until now
